[package]
name        = "nanpure"
version     = "0.2.0"
authors     = ["Rodrigo Montegasppα Cacilhας <montegasppa@cacilhas.info"]
license     = "BSD-3-Clause"
readme      = "README.md"
homepage    = "https://crates.io/crates/nanpure"
repository  = "https://github.com/cacilhas/nanpure"
keywords    = ["raylib", "sudoku"]
categories  = ["Games"]
description = "Yet another sudoku playing game."
edition     = "2021"

[profile.release]
opt-level     = "s"
codegen-units = 1
debug = false
lto   = true
rpath = false
strip = true

[dependencies]
color-eyre = "0.6"
eyre = "0.6"
raylib-ffi = "5.0"
static_init = "1.0"
walkdir = "2.5"
