[package]
name        = "nanpure"
version     = "0.2.3"
authors     = ["Rodrigo Montegasppα Cacilhας <montegasppa@cacilhas.info"]
license     = "BSD-3-Clause"
readme      = "README.md"
homepage    = "https://crates.io/crates/nanpure"
repository  = "https://github.com/cacilhas/nanpure"
keywords    = ["raylib", "sudoku"]
categories  = ["Games"]
description = "Yet another sudoku playing game."
edition     = "2021"

[profile.release]
opt-level     = "s"
codegen-units = 1
panic = "abort"
debug = false
lto   = true
rpath = false
strip = true

[dependencies]
color-eyre = "0.6"
eyre = "0.6"
hecs = "0.10"
raylib-ffi = "5.0"
static_init = "1.0"
toml = "0.8"
walkdir = "2.5"

[dependencies.serde]
version = "1.0"
features = ["derive"]
